
services:
  mongo:
    image: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - TZ=Europe/Moscow
    volumes:
      - ./data/db:/data/db
  syslogcollector:
    image: ciscoliveru/syslogcollector
    environment:
      - MONGOURL=mongodb://mongo:27017
      - TZ=Europe/Moscow
    depends_on:
      - mongo
    ports:
      - 514:514/udp
  syslogapi:
    image: ciscoliveru/syslogapi
    environment:
      - MONGOURL=mongodb://mongo:27017
      - TZ=Europe/Moscow
    depends_on:
      - mongo
    ports:
      - 8181:80
